version: '3.7'
services:
  api:
#    image: chi-rest-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8000"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '4'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 100M