version: "3.8"
volumes:
  postgres_data:

services:
  postgresql:
    image: postgres:14.8-bullseye
    command: postgres -c max_connections=1000 -c jit=off -c synchronous_commit=off -c shared_buffers=1GB -c wal_writer_delay=1s -c wal_buffers=15MB
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=example_db
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.75'
          memory: 750M