basePath: /
definitions:
  account.CreateAccountItem:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  auth.LoginItem:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  utils.Response:
    properties:
      data: {}
      message:
        type: string
      status:
        type: integer
    type: object
host: 0.0.0.0:8000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example APIII
  version: "2.0"
paths:
  /accounts:
    get:
      consumes:
      - application/json
      description: get list account.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
      security:
      - BearerAuth: []
      summary: Get List Account
      tags:
      - Account
    post:
      consumes:
      - application/json
      description: create account.
      parameters:
      - description: account
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/account.CreateAccountItem'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
      security:
      - BearerAuth: []
      summary: Create Account
      tags:
      - Account
  /accounts/{id}:
    delete:
      consumes:
      - application/json
      description: delete account.
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
      security:
      - BearerAuth: []
      summary: Delete Account
      tags:
      - Account
    put:
      consumes:
      - application/json
      description: update account.
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      - description: account
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/account.CreateAccountItem'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
      security:
      - BearerAuth: []
      summary: Update Account
      tags:
      - Account
  /auth/login:
    post:
      consumes:
      - application/json
      description: login account.
      parameters:
      - description: Login
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/auth.LoginItem'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
      summary: Login
      tags:
      - Auth
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
